controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

client_index:
    path: /clients
    controller: App\Controller\ClientController::index
